# Generated by Django 5.0.2 on 2024-03-24 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionParliamentaryCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_candidates', to='candidates.parliamentarycandidate')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionPresidentialCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('parliamentary_seat', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidential_candidates', to='candidates.presidentialcandidate')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, choices=[('1992', '1992'), ('1996', '1996'), ('2000', '2000'), ('2000R', '2000R'), ('2004', '2004'), ('2008', '2008'), ('2008R', '2008R'), ('2012', '2012'), ('2016', '2016'), ('2020', '2020'), ('2024', '2024')], max_length=255, null=True)),
                ('first_runner_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_presidential_first_runner_up', to='elections.electionpresidentialcandidate')),
                ('second_runner_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_presidential_second_runner_up', to='elections.electionpresidentialcandidate')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_presidential_winner', to='elections.electionpresidentialcandidate')),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentaryCandidateConstituencyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('won', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('constituency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidate_constituency', to='regions.constituency')),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidates_constituency', to='elections.election')),
                ('parlia_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_candidate_consti_score', to='elections.electionparliamentarycandidate')),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentaryCandidatePollingStationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('won', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidates_polling_station', to='elections.election')),
                ('parlia_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_candidate_polling_station_score', to='elections.electionparliamentarycandidate')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidate_polling_station', to='regions.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentaryCandidateRegionalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.BooleanField(default=False)),
                ('total_votes', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidates_regional', to='elections.election')),
                ('parlia_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_candidate', to='elections.electionparliamentarycandidate')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidate_region', to='regions.region')),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentaryCandidateZonalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('won', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidates_zone', to='elections.election')),
                ('parlia_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_candidate_zone_score', to='elections.electionparliamentarycandidate')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidate_zone', to='regions.zone')),
            ],
        ),
        migrations.CreateModel(
            name='PresidentialCandidateConstituencyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('won', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('constituency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidate_constituency', to='regions.constituency')),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidates_constituency', to='elections.election')),
                ('prez_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidential_candidate_consti_score', to='elections.electionpresidentialcandidate')),
            ],
        ),
        migrations.CreateModel(
            name='PresidentialCandidatePollingStationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('won', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidates_polling_station', to='elections.election')),
                ('prez_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidential_candidate_polling_station_score', to='elections.electionpresidentialcandidate')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidate_polling_station', to='regions.zone')),
            ],
        ),
        migrations.CreateModel(
            name='PresidentialCandidateRegionalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('won', models.BooleanField(default=False)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('parliamentary_seat', models.IntegerField(default=0)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidates_regional', to='elections.election')),
                ('prez_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidential_candidate', to='elections.electionpresidentialcandidate')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidate_region', to='regions.region')),
            ],
        ),
        migrations.CreateModel(
            name='PresidentialCandidateZonalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('won', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidates_zone', to='elections.election')),
                ('prez_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidential_candidate_zone_score', to='elections.electionpresidentialcandidate')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidate_zone', to='regions.zone')),
            ],
        ),
    ]
