# Generated by Django 5.0.2 on 2024-03-24 06:06

import django.db.models.deletion
import regions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('constituency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('central_lat', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('central_lng', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_station_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('polling_station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('central_lat', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('central_lng', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('region_name', models.CharField(blank=True, choices=[('Ahafo', 'Ahafo'), ('Ashanti', 'Ashanti'), ('Bono East', 'Bono East'), ('Brong Ahafo', 'Brong Ahafo'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Greater Accra', 'Greater Accra'), ('Northern', 'Northern'), ('North East', 'North East'), ('Oti', 'Oti'), ('Savannah', 'Savannah'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('Volta', 'Volta'), ('Western', 'Western'), ('Western North', 'Western North')], max_length=255, null=True)),
                ('initials', models.CharField(blank=True, max_length=255, null=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to=regions.models.upload_region_image_path)),
                ('central_lat', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('central_lng', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConstituencyVotersParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_voters', models.IntegerField(default=0)),
                ('voters', models.IntegerField(default=0)),
                ('turn_out', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituency_registered_voters', to='regions.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='PollingStationVotersParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_voters', models.IntegerField(default=0)),
                ('voters', models.IntegerField(default=0)),
                ('turn_out', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_station_registered_voters', to='regions.pollingstation')),
            ],
        ),
        migrations.AddField(
            model_name='constituency',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_constituencies', to='regions.region'),
        ),
        migrations.CreateModel(
            name='RegionalVotersParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_voters', models.IntegerField(default=0)),
                ('voters', models.IntegerField(default=0)),
                ('turn_out', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_registered_voters', to='regions.region')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('zone_name', models.CharField(blank=True, max_length=255, null=True)),
                ('central_lat', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('central_lng', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituency_zones', to='regions.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='ZonalVotersParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_voters', models.IntegerField(default=0)),
                ('voters', models.IntegerField(default=0)),
                ('turn_out', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonal_registered_voters', to='regions.zone')),
            ],
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_polling_stations', to='regions.zone'),
        ),
    ]
