# Generated by Django 5.0.2 on 2024-03-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingstationvotersparticipation',
            name='turn_out_percent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='pollingstationvotersparticipation',
            name='turn_out',
            field=models.IntegerField(default=0),
        ),
    ]
