# Generated by Django 5.0.2 on 2024-03-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_pollingstationvotersparticipation_turn_out_percent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollingstationvotersparticipation',
            old_name='turn_out',
            new_name='non_voters',
        ),
    ]
