# Generated by Django 5.0.2 on 2024-03-29 12:15

import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to=user_profile.models.upload_id_card_path),
        ),
    ]
